name: TonieFinder
options:
  minimumXcodeGenVersion: 2.44.1
settings:
  base:
    PRODUCT_BUNDLE_IDENTIFIER: com.falko.toniefinder
    SWIFT_VERSION: 5.0
    MARKETING_VERSION: 0.1.0
    CURRENT_PROJECT_VERSION: 1
    DEVELOPMENT_TEAM: ""
packages: {}
targets:
  TonieFinder:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: TonieFinder/Sources
      - path: TonieFinder/Resources
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_CFBundleDisplayName: Tonie Finder
        INFOPLIST_KEY_NSAppTransportSecurity_NSAllowsArbitraryLoads: YES
        "INFOPLIST_KEY_TF_API_BASE_URL[sdk=iphonesimulator*]": "http://127.0.0.1:8787/api"
        "INFOPLIST_KEY_TF_API_BASE_URL[sdk=iphoneos*]": "http://192.168.178.100:8787/api"
        TARGETED_DEVICE_FAMILY: "1,2"
    scheme:
      testTargets:
        - TonieFinderTests

  TonieFinderTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: TonieFinder/Tests
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
    dependencies:
      - target: TonieFinder
